varReference:
- kind: ClusterRoleBinding
  group: rbac.authorization.k8s.io
  path: subjects/name
- kind: RoleBinding
  group: rbac.authorization.k8s.io
  path: subjects/name

namespace:
- kind: ClusterRoleBinding
  group: rbac.authorization.k8s.io
  path: subjects/namespace
- kind: RoleBinding
  group: rbac.authorization.k8s.io
  path: subjects/namespace
